<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="LinqKit" Version="1.2.3" />
    <PackageReference Include="MySql.Data" Version="8.0.29" />
    <PackageReference Include="RestSharp" Version="107.2.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.25.1" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.8" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Text.Json" Version="8.0.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Core\CMS.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Identity\" />
    <Folder Include="Logging\" />
  </ItemGroup>
</Project>